name: Deploy to AWS Lambda

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set NEXTAUTH_URL
        run: |
          echo "NEXTAUTH_URL=https://example.com" >> $GITHUB_ENV

      - name: Write .env.local file
        run: |
          echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - name: Install dependencies
        run: |
          npm ci
          npm install aws-cdk-lib

      - name: Build Next.js app
        run: npm run build
        env:
          NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          npx aws-cdk deploy --require-approval never --app ./next-aws.js
        env:
          NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}